# You won't typically have to change the following two lines!
metasheet: './metasheet.csv'
ref: './ref.yaml'

# ALIGNER: if you want to use STAR, set your aligner as 'STAR' (not support yet)
# OTHERWISE leave it as 'salmon' (default)
# {'salmon', 'STAR'}
aligner: 'salmon'

# #Tell us what assembly to use (!! MUST be defined in chips/ref.yaml !!)
# typically we support {'mm10', 'hg38'}
assembly: 'mm10'

# Whethe you want to trim your RNA-seq reads adaptor first.
# {True, False}
trim: True

# Whether you want to process lisa on your differential expression genes.
# Please make sure on you have already installed lisa by the instruction in README.md
# {True, False}
lisa: True

# If check_compare is False, DEAP will only trim and align samples that have enough replicates
# otherwise will trim and align samples but won't process differential expression.
check_compare: False

# DEFINE the samples - each sample should have a name, e.g. SAMPLE1
# and a path to the input file, e.g. data/sample1.fastq.gz
# VALID INPUTS: fastq, fastq.gz, CEL.gz
# NOTE: for PAIRED-END fastq/fastq.gz, give both pairs to the sample:
# SAMPLE_1_PE:
#   - data/sample1_pair1.fastq
#   - data/sample1_pair2.fastq
# WARNING: DO not mix Paired-END and Single-End samples!!!
# ALSO: having the string '.' in your sample name will throw an ERROR
# '.' causes Rscripts chop off names
# If you want to use geo_start.py, delete or comment whole "sample" part.
samples:
  SAMPLE1:
    - data/SAMPLE1_R1.fastq.gz
    - data/SAMPLE2_R2.fastq.gz
  SAMPLE2:
    - data/SAMPLE1_R1.fastq.gz
    - data/SAMPLE2_R2.fastq.gz
  SAMPLE3:
    - data/SAMPLE3.fastq.gz
  SAMPLE4:
    - data/SAMPLE4.fastq.gz
  SAMPLE5:
    - data/SAMPLE5.fastq.gz
  SAMPLE6:
    - data/SAMPLE6.fastq.gz
  
