name: DEAP
channels:
- conda-forge
- bioconda
- liulab-dfci
- defaults

dependencies:
# GENERAL
- snakemake=8.18.0
- samtools
- python=3.12.3
- r-base=4.3.3
- r-biocmanager
- glib=2.80.2

# trim.snakefile
- trim-galore=0.6.10

# align_STAR.snakefile
- star=2.7.11b
- star-fusion>=0.5.4
- subread=2.0.6

# rsem.snakefile
- rsem

# align_salmon.snakefile
- salmon=1.10.3
- deeptools=3.5.5
# expression.snakefile
# 
# - bioconductor-deseq2>=1.12.1
- bioconductor-limma
# - bioconductor-edger
# - bioconductor-tximport
- pytximport>=0.7.0
- bioconductor-org.hs.eg.db
- bioconductor-org.mm.eg.db
- bioconductor-org.rn.eg.db
- bioconductor-affy
- bioconductor-affyplm
# - bioconductor-sva
# - bioconductor-oligo
- r-optparse
- r-ggplot2=3.1.1
- r-ggrepel
- r-readr
- r-calibrate
- pydeseq2=0.4.10
- anndata=0.10.5

- scikit-learn
- pandas=2.2.2
- numpy=1.26.4
- adjusttext # for plot
- matplotlib

#gsea.snakefile
- bioconductor-clusterprofiler
- gseapy

#lisa.snakefile
- lisa2=2.3.2
- scipy=1.12.0

- pip:
  - inmoose==0.7.1 # 0.3.1 has bug on batch effect, count_pd return array
