name: DEAP
channels:
- bioconda
- conda-forge
- defaults

dependencies:
#GENERAL
- snakemake=5.4.5
- samtools
- python>=3.5.2
- r>=3.5.1

#align_STAR.snakefile
# - star>=2.5.3a
# - star-fusion=0.5.4

# trim.snakefile
- trim-galore>=0.6.2

# align_salmon.snakefile
- salmon=0.14.1

#expression.snakefile
- bioconductor-deseq2>=1.12.1
- bioconductor-limma
# - bioconductor-edger
# - bioconductor-tximport
- bioconductor-org.Hs.eg.db
- bioconductor-org.Mm.eg.db
# - bioconductor-affy
# - bioconductor-affyplm
- bioconductor-sva
# - bioconductor-oligo=1.44.0
- r-optparse
- r-ggplot2>=3.1.1
- r-ggrepel
# - r-readr
# - r-calibrate

#gsea.snakefile
- bioconductor-clusterprofiler

#lisa.snakefile

